package com.circlenet.domain.finance;
import java.math.*;import java.nio.charset.StandardCharsets;import java.security.MessageDigest;import java.time.*;import java.util.*;import java.util.regex.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.web.server.ResponseStatusException;
@Service public class FinanceService{
 private static final Set<String>CATEGORIES=Set.of("SHOPPING","GROCERIES","HEALTH","INVESTMENT","HOUSING","TRANSPORT","FOOD","UTILITIES","EDUCATION","ENTERTAINMENT","INCOME","OTHER");
 private static final Pattern AMOUNT=Pattern.compile("(?i)(?:inr|rs\\.?|₹)\\s*([0-9,]+(?:\\.[0-9]{1,2})?)|([0-9,]+(?:\\.[0-9]{1,2})?)\\s*(?:inr|rs\\.?|₹)");
 private final FinancialTransactionRepository repo;public FinanceService(FinancialTransactionRepository r){repo=r;}
 public record Input(BigDecimal amount,String direction,String category,String merchant,String description,Instant occurredAt,String source,String smsBody,String smsSender){}public record Transaction(Long id,BigDecimal amount,String direction,String category,String merchant,String description,Instant occurredAt,String source){}public record Summary(BigDecimal income,BigDecimal spending,BigDecimal net,Map<String,BigDecimal> categories,List<Transaction> transactions,List<String> suggestions,String disclaimer){}
 public Transaction add(Long user,Input in){if(in==null)bad("Transaction is required");String source=clean(in.source(),"MANUAL").toUpperCase();if("SMS".equals(source))return sms(user,in);return save(user,in.amount(),clean(in.direction(),"EXPENSE"),category(in.category(),in.description()),in.merchant(),in.description(),in.occurredAt(),source,null);}
 private Transaction sms(Long user,Input in){String body=clean(in.smsBody(),"");if(body.length()<8||body.length()>2000)bad("SMS text must be between 8 and 2000 characters");Matcher m=AMOUNT.matcher(body);if(!m.find())bad("No INR amount was found in this message");BigDecimal amount=new BigDecimal((m.group(1)!=null?m.group(1):m.group(2)).replace(",",""));String direction=body.toLowerCase().matches(".*(credited|received|deposit|salary).*" )?"INCOME":"EXPENSE";String fingerprint=hash(clean(in.smsSender(),"")+"|"+body+"|"+(in.occurredAt()==null?"":in.occurredAt()));return repo.findByUserIdAndSourceFingerprint(user,fingerprint).map(this::dto).orElseGet(()->save(user,amount,direction,category(null,body),merchant(body),"Imported financial SMS",in.occurredAt(),"SMS",fingerprint));}
 public Summary summary(Long user,YearMonth month){ZoneId zone=ZoneOffset.UTC;Instant from=month.atDay(1).atStartOfDay(zone).toInstant(),to=month.plusMonths(1).atDay(1).atStartOfDay(zone).toInstant();List<Transaction> tx=repo.findByUserIdAndOccurredAtBetweenOrderByOccurredAtDesc(user,from,to).stream().map(this::dto).toList();BigDecimal income=sum(tx,"INCOME"),spending=sum(tx,"EXPENSE");Map<String,BigDecimal> cats=new LinkedHashMap<>();tx.stream().filter(x->"EXPENSE".equals(x.direction())).forEach(x->cats.merge(x.category(),x.amount(),BigDecimal::add));return new Summary(income,spending,income.subtract(spending),cats,tx,suggestions(income,spending,cats),"Educational guidance only. CircleNet is not a financial adviser; review decisions with a qualified professional.");}
 public void delete(Long user,Long id){FinancialTransactionEntity e=repo.findById(id).filter(x->x.getUserId().equals(user)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));repo.delete(e);}
 private Transaction save(Long user,BigDecimal amount,String direction,String category,String merchant,String desc,Instant at,String source,String fingerprint){if(amount==null||amount.signum()<=0)bad("Amount must be greater than zero");direction=direction.toUpperCase();if(!Set.of("EXPENSE","INCOME").contains(direction))bad("Direction must be EXPENSE or INCOME");if(!Set.of("MANUAL","SMS","IMPORT").contains(source))bad("Unsupported source");FinancialTransactionEntity e=new FinancialTransactionEntity();e.setUserId(user);e.setAmount(amount.setScale(2,RoundingMode.HALF_UP));e.setDirection(direction);e.setCategory("INCOME".equals(direction)?"INCOME":category);e.setMerchant(trim(merchant,160));e.setDescription(trim(desc,500));e.setOccurredAt(at==null?Instant.now():at);e.setSource(source);e.setSourceFingerprint(fingerprint);return dto(repo.save(e));}
 private String category(String requested,String text){if(requested!=null&&CATEGORIES.contains(requested.toUpperCase()))return requested.toUpperCase();String s=clean(text,"").toLowerCase();if(s.matches(".*(amazon|flipkart|mall|shopping|store).*"))return"SHOPPING";if(s.matches(".*(grocery|supermarket|mart|vegetable).*"))return"GROCERIES";if(s.matches(".*(hospital|pharmacy|medical|doctor|clinic).*"))return"HEALTH";if(s.matches(".*(mutual fund|sip|stock|demat|investment).*"))return"INVESTMENT";if(s.matches(".*(restaurant|swiggy|zomato|cafe|food).*"))return"FOOD";if(s.matches(".*(uber|ola|fuel|petrol|metro).*"))return"TRANSPORT";if(s.matches(".*(electricity|mobile|broadband|utility|recharge).*"))return"UTILITIES";return"OTHER";}
 private String merchant(String body){Matcher m=Pattern.compile("(?i)(?:at|to)\\s+([A-Z0-9][A-Z0-9 &._-]{2,30})").matcher(body);return m.find()?m.group(1).trim():"SMS transaction";}
 private List<String> suggestions(BigDecimal income,BigDecimal spend,Map<String,BigDecimal> cats){List<String>s=new ArrayList<>();if(income.signum()==0)s.add("Add income transactions to calculate a meaningful savings rate.");else{BigDecimal rate=income.subtract(spend).multiply(BigDecimal.valueOf(100)).divide(income,1,RoundingMode.HALF_UP);s.add("Your recorded savings rate is "+rate+"%. Consider building an emergency fund before higher-risk investing.");if(rate.compareTo(BigDecimal.valueOf(20))<0)s.add("Review your largest flexible category and set a realistic monthly limit before increasing investments.");else s.add("If your emergency fund and high-interest debts are covered, consider diversified, low-cost investments suited to your goals and risk tolerance.");}cats.entrySet().stream().max(Map.Entry.comparingByValue()).ifPresent(x->s.add(x.getKey()+" is your largest spending category this month at ₹"+x.getValue()+"."));return s;}
 private BigDecimal sum(List<Transaction>x,String d){return x.stream().filter(t->d.equals(t.direction())).map(Transaction::amount).reduce(BigDecimal.ZERO,BigDecimal::add);}private Transaction dto(FinancialTransactionEntity e){return new Transaction(e.getId(),e.getAmount(),e.getDirection(),e.getCategory(),e.getMerchant(),e.getDescription(),e.getOccurredAt(),e.getSource());}private static String clean(String x,String d){return x==null||x.isBlank()?d:x.trim();}private static String trim(String x,int n){return x==null?null:x.trim().substring(0,Math.min(n,x.trim().length()));}private static void bad(String s){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,s);}private static String hash(String s){try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(s.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
}
