'use client';
import {FormEvent,useCallback,useEffect,useRef,useState}from'react';
import {useRouter}from'next/navigation';
import {addHealthReport,analyzeHealthReport,deleteHealthReport,fetchHealthDashboard,fetchSocialFeed,fetchSocialMedia,hasAuthSession,HealthDashboard,isUnauthorizedError,SocialPost}from'../lib/api';
type Row={metricName:string;value:string;unit:string;referenceMin:string;referenceMax:string};const blank=():Row=>({metricName:'',value:'',unit:'',referenceMin:'',referenceMax:''});
function TrendChart({trend}:{trend:HealthDashboard['trends'][number]}){const values=trend.points.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),span=Math.max(1,max-min),points=trend.points.map((x,i)=>`${trend.points.length===1?50:5+i*90/(trend.points.length-1)},${90-(x.value-min)/span*70}`).join(' ');return <article className="card health-trend"><header><h3>{trend.metricName}</h3><b>{trend.points.at(-1)?.value} {trend.unit}</b></header><svg viewBox="0 0 100 100" role="img" aria-label={`${trend.metricName} trend`} preserveAspectRatio="none"><polyline points={points}/>{trend.points.map((x,i)=><circle key={`${x.date}-${i}`} cx={trend.points.length===1?50:5+i*90/(trend.points.length-1)} cy={90-(x.value-min)/span*70} r="2.2"/>)}</svg><footer>{trend.points.map(x=><small key={x.reportId}>{new Date(x.date).toLocaleDateString()} · {x.value}</small>)}</footer></article>}
export default function HealthPage(){const router=useRouter(),file=useRef<HTMLInputElement>(null),[data,setData]=useState<HealthDashboard>(),[docs,setDocs]=useState<SocialPost[]>([]),[rows,setRows]=useState<Row[]>([blank()]),[error,setError]=useState(''),[open,setOpen]=useState(false),[analyzing,setAnalyzing]=useState(false);
 const load=useCallback(async()=>{try{const[d,feed]=await Promise.all([fetchHealthDashboard(),fetchSocialFeed()]);setData(d);setDocs(feed.filter(x=>x.mine&&x.audience==='PRIVATE'&&!!x.mediaUrl));}catch(e){if(isUnauthorizedError(e))router.replace('/auth');else setError((e as Error).message);}},[router]);useEffect(()=>{if(!hasAuthSession())router.replace('/auth');else void load();},[load,router]);
 async function upload(chosen?:File){if(!chosen)return;setError('');setAnalyzing(true);try{await analyzeHealthReport(chosen);await load();}catch(e){setError((e as Error).message);}finally{setAnalyzing(false);if(file.current)file.current.value='';}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget,v=new FormData(form);try{await addHealthReport({sourcePostId:v.get('sourcePostId')?Number(v.get('sourcePostId')):undefined,reportName:String(v.get('reportName')),laboratory:String(v.get('laboratory')),collectedOn:String(v.get('collectedOn')),notes:String(v.get('notes')),measurements:rows.filter(x=>x.metricName&&x.value&&x.unit).map(x=>({metricName:x.metricName,value:Number(x.value),unit:x.unit,referenceMin:x.referenceMin?Number(x.referenceMin):undefined,referenceMax:x.referenceMax?Number(x.referenceMax):undefined}))});form.reset();setRows([blank()]);setOpen(false);await load();}catch(e){setError((e as Error).message);}}
 return <main className="health-page"><header className="health-hero"><div><small>PERSONAL ASSISTANT · HEALTH</small><h1>Health records & trends</h1><p>Upload a complete diagnostic report. MyAaptha reads all numeric parameters, records their date and shows how each value changes over time.</p></div><div className="health-actions"><input ref={file} hidden type="file" accept="application/pdf,image/jpeg,image/png" onChange={e=>void upload(e.target.files?.[0])}/><button className="btn btn-primary" disabled={analyzing} onClick={()=>file.current?.click()}>{analyzing?'Reading report…':'Upload report'}</button><button className="btn" onClick={()=>setOpen(x=>!x)}>{open?'Close manual entry':'Enter manually'}</button></div></header>
 {error&&<p className="network-message error-message" role="alert">{error}</p>}{analyzing&&<section className="health-disclaimer" role="status">Reading every page and extracting laboratory values. This may take a minute.</section>}
 {open&&<form className="card health-form" onSubmit={submit}><h2>Add diagnostic report manually</h2><label>Report name<input required name="reportName" placeholder="Annual blood test"/></label><label>Laboratory<input name="laboratory"/></label><label>Collection date<input required name="collectedOn" type="date"/></label><label>Existing private diary document<select name="sourcePostId"><option value="">No linked document</option>{docs.map(x=><option key={x.id} value={x.id}>{x.mediaName||x.caption}</option>)}</select></label><label className="wide">Notes<textarea name="notes" maxLength={1000}/></label><section className="health-measurements"><header><h3>Measurements</h3><button type="button" onClick={()=>setRows(x=>[...x,blank()])}>＋ Add measurement</button></header>{rows.map((row,index)=><div key={index}><input aria-label="Metric" placeholder="Hemoglobin" value={row.metricName} onChange={e=>setRows(x=>x.map((r,i)=>i===index?{...r,metricName:e.target.value}:r))}/><input aria-label="Value" type="number" step="any" placeholder="Value" value={row.value} onChange={e=>setRows(x=>x.map((r,i)=>i===index?{...r,value:e.target.value}:r))}/><input aria-label="Unit" placeholder="g/dL" value={row.unit} onChange={e=>setRows(x=>x.map((r,i)=>i===index?{...r,unit:e.target.value}:r))}/><input aria-label="Reference minimum" type="number" step="any" placeholder="Lab min" value={row.referenceMin} onChange={e=>setRows(x=>x.map((r,i)=>i===index?{...r,referenceMin:e.target.value}:r))}/><input aria-label="Reference maximum" type="number" step="any" placeholder="Lab max" value={row.referenceMax} onChange={e=>setRows(x=>x.map((r,i)=>i===index?{...r,referenceMax:e.target.value}:r))}/></div>)}</section><button className="btn btn-primary">Save report and measurements</button></form>}
 <section className="health-disclaimer" role="note">ⓘ {data?.disclaimer}</section><section className="health-trends"><h2>Measurement trends</h2><div>{data?.trends.map(x=><TrendChart key={`${x.metricName}-${x.unit}`} trend={x}/>)}</div>{!data?.trends.length&&<p>No measurements yet. Upload a diagnostic report to begin tracking values.</p>}</section>
 <section className="health-reports"><h2>Diagnostic reports</h2>{data?.reports.map(r=><article className="card" key={r.id}><header><div><h3>{r.reportName}</h3><small>{r.laboratory||'Laboratory not specified'} · {new Date(r.collectedOn).toLocaleDateString()}</small></div><button aria-label="Delete report record" onClick={async()=>{await deleteHealthReport(r.id);await load();}}>×</button></header>{r.sourceMediaName&&<button className="health-document" onClick={async()=>{if(!r.sourceMediaUrl)return;const blob=await fetchSocialMedia(r.sourceMediaUrl),url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000);}}>▤ {r.sourceMediaName}</button>}<div className="health-values">{r.measurements.map(m=><span className={`range-${m.rangeStatus.toLowerCase()}`} key={m.id}><b>{m.metricName}</b>{m.value} {m.unit}<small>{m.rangeStatus==='IN_RANGE'?'Within printed lab range':`${m.rangeStatus.toLowerCase()} printed lab range`}</small>{m.suggestion&&m.rangeStatus!=='IN_RANGE'&&<em>{m.suggestion}</em>}</span>)}</div></article>)}</section>
 </main>}
