version: 2
updates:
  - package-ecosystem: maven
    directory: /backend/spring-boot-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: npm
    directory: /frontend/nextjs-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: pub
    directory: /mobile/flutter-app
    schedule:
      interval: weekly
    open-pull-requests-limit: 10

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
