package com.circlenet.domain.trust;

import com.circlenet.domain.circle.CircleMediaStorage;
import com.circlenet.domain.notification.*;
import com.circlenet.domain.profile.UserProfileRepository;
import com.circlenet.domain.social.SocialPostRepository;
import com.circlenet.domain.user.UserRepository;
import com.circlenet.domain.user.model.UserEntity;
import java.time.*; import java.util.*;
import org.springframework.core.io.Resource; import org.springframework.http.HttpStatus; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.server.ResponseStatusException;

@Service @Transactional public class TrustService {
 private static final int MAX_STARS=5, MAX_ROLE_MODELS=20;
 private final TrustedPersonRepository trusted; private final RoleModelFollowRepository follows; private final EmergencyAccessRequestRepository requests; private final EmergencyApprovalRepository approvals; private final EmergencyAccessEventRepository events; private final UserRepository users; private final UserProfileRepository profiles; private final SocialPostRepository posts; private final CircleMediaStorage media; private final NotificationService notifications;
 public TrustService(TrustedPersonRepository t,RoleModelFollowRepository f,EmergencyAccessRequestRepository r,EmergencyApprovalRepository a,EmergencyAccessEventRepository e,UserRepository u,UserProfileRepository p,SocialPostRepository sp,CircleMediaStorage m,NotificationService n){trusted=t;follows=f;requests=r;approvals=a;events=e;users=u;profiles=p;posts=sp;media=m;notifications=n;}
 public record Person(Long userId,String displayName,String profilePhoto,String kind,long followerCount,Instant addedAt){}
 public record EmergencyRequest(Long id,Long ownerUserId,String ownerName,Long requesterUserId,String requesterName,String reason,String status,int approvals,int requiredApprovals,Instant createdAt,Instant expiresAt,Instant grantedUntil){}
 public record EmergencyDocument(Long id,String caption,String mediaName,String mediaType,Long mediaSize,String mediaUrl,Instant createdAt){}
 public record Attachment(Resource resource,String name,String type){}
 public List<Person> mine(Long user,String kind){String k=kind(kind);return trusted.findByOwnerUserIdAndKindOrderByCreatedAtDesc(user,k).stream().map(this::person).toList();}
 public List<Person> inbound(Long user,String kind){String k=kind(kind);return trusted.findByTrustedUserIdAndKindOrderByCreatedAtDesc(user,k).stream().map(x->publicPerson(x.getOwnerUserId(),k,x.getCreatedAt())).toList();}
 public Person add(Long owner,Long target,String kind){String k=kind(kind);if(target==null||owner.equals(target))bad("Choose another account");users.findById(target).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Account not found"));long limit="STAR".equals(k)?MAX_STARS:MAX_ROLE_MODELS;if(trusted.countByOwnerUserIdAndKind(owner,k)>=limit)bad("You have reached the "+k.toLowerCase().replace('_',' ')+" limit");var entity=trusted.findByOwnerUserIdAndTrustedUserIdAndKind(owner,target,k).orElseGet(()->{var x=new TrustedPersonEntity();x.setOwnerUserId(owner);x.setTrustedUserId(target);x.setKind(k);return trusted.save(x);});notifications.notify(new NotificationCommand(target,"STAR".equals(k)?"STAR_MEMBER":"ROLE_MODEL",name(owner)+("STAR".equals(k)?" trusts you as a Star Member":" added you as a Role Model"),"Open your Trust center for details.","/trust","TRUSTED_PERSON",entity.getId()));return person(entity);}
 public void remove(Long owner,Long target,String kind){trusted.findByOwnerUserIdAndTrustedUserIdAndKind(owner,target,kind(kind)).ifPresent(trusted::delete);}
 @Transactional(readOnly=true) public List<Person> roleModels(Long viewer){return trusted.findAll().stream().filter(x->"ROLE_MODEL".equals(x.getKind())).collect(java.util.stream.Collectors.toMap(TrustedPersonEntity::getTrustedUserId,x->x,(a,b)->a,LinkedHashMap::new)).values().stream().map(this::person).toList();}
 public Person follow(Long user,Long roleModel){if(user.equals(roleModel))bad("You cannot follow yourself");if(trusted.findByTrustedUserIdAndKindOrderByCreatedAtDesc(roleModel,"ROLE_MODEL").isEmpty())bad("This member is not a Role Model");var f=follows.findByFollowerUserIdAndRoleModelUserId(user,roleModel).orElseGet(()->{var x=new RoleModelFollowEntity();x.setFollowerUserId(user);x.setRoleModelUserId(roleModel);return follows.save(x);});notifications.notify(new NotificationCommand(roleModel,"ROLE_MODEL_FOLLOW",name(user)+" followed you","Followers can contact you inside CircleNet; private contact details remain hidden.","/messages?userId="+user,"USER",user));return publicPerson(roleModel,"ROLE_MODEL",f.getCreatedAt());}
 public void unfollow(Long user,Long roleModel){follows.findByFollowerUserIdAndRoleModelUserId(user,roleModel).ifPresent(follows::delete);}
 public EmergencyRequest request(Long requester,Long owner,String reason){if(trusted.findByOwnerUserIdAndTrustedUserIdAndKind(owner,requester,"STAR").isEmpty())forbid("Only a Star Member can request emergency access");String clean=reason==null?"":reason.trim();if(clean.length()<20||clean.length()>1000)bad("Describe the emergency in 20 to 1000 characters");long stars=trusted.countByOwnerUserIdAndKind(owner,"STAR");if(stars<2)bad("The owner must configure at least two Star Members");var r=new EmergencyAccessRequestEntity();r.setOwnerUserId(owner);r.setRequesterUserId(requester);r.setReason(clean);r.setRequiredApprovals(2);r.setExpiresAt(Instant.now().plus(Duration.ofHours(24)));r=requests.save(r);decide(requester,r.getId(),true);notifications.notify(new NotificationCommand(owner,"EMERGENCY_ACCESS","Emergency access requested by "+name(requester),clean,"/trust","EMERGENCY_REQUEST",r.getId()));return dto(r);}
 public EmergencyRequest decide(Long user,Long requestId,boolean approved){var r=requests.findById(requestId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Request not found"));refresh(r);if(!"PENDING".equals(r.getStatus()))bad("This request is no longer pending");if(trusted.findByOwnerUserIdAndTrustedUserIdAndKind(r.getOwnerUserId(),user,"STAR").isEmpty())forbid("Only the owner's Star Members can decide");var key=new EmergencyApprovalEntity.Key();key.requestId=requestId;key.approverUserId=user;if(approvals.existsById(key))bad("You already decided this request");var a=new EmergencyApprovalEntity();a.setRequestId(requestId);a.setApproverUserId(user);a.setApproved(approved);approvals.save(a);if(!approved)r.setStatus("REJECTED");else if(approvals.countByRequestIdAndApprovedTrue(requestId)>=r.getRequiredApprovals()){r.setStatus("APPROVED");r.setGrantedUntil(Instant.now().plus(Duration.ofHours(1)));}requests.save(r);event(r,user,approved?"APPROVED":"REJECTED",null);return dto(r);}
 public List<EmergencyRequest> emergencyRequests(Long user){return requests.findAll().stream().filter(r->r.getOwnerUserId().equals(user)||r.getRequesterUserId().equals(user)||trusted.findByOwnerUserIdAndTrustedUserIdAndKind(r.getOwnerUserId(),user,"STAR").isPresent()).sorted(Comparator.comparing(EmergencyAccessRequestEntity::getCreatedAt).reversed()).peek(this::refresh).map(this::dto).toList();}
 public List<EmergencyDocument> documents(Long requester,Long requestId){var r=grant(requester,requestId);event(r,requester,"DOCUMENT_LIST_VIEWED",null);return posts.findTop100ByOrderByCreatedAtDesc().stream().filter(p->p.getAuthorUserId().equals(r.getOwnerUserId())&&"PRIVATE".equals(p.getAudience())&&p.getMediaKey()!=null).map(p->new EmergencyDocument(p.getId(),p.getCaption(),p.getMediaName(),p.getMediaType(),p.getMediaSize(),"/api/trust/emergencies/"+requestId+"/documents/"+p.getId()+"/media",p.getCreatedAt())).toList();}
 public Attachment document(Long requester,Long requestId,Long postId){var r=grant(requester,requestId);var p=posts.findById(postId).filter(x->x.getAuthorUserId().equals(r.getOwnerUserId())&&"PRIVATE".equals(x.getAudience())&&x.getMediaKey()!=null).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Document not found"));event(r,requester,"DOCUMENT_OPENED",postId);return new Attachment(media.load(p.getMediaKey()),p.getMediaName(),p.getMediaType());}
 private EmergencyAccessRequestEntity grant(Long user,Long id){var r=requests.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Request not found"));refresh(r);if(!r.getRequesterUserId().equals(user)||trusted.findByOwnerUserIdAndTrustedUserIdAndKind(r.getOwnerUserId(),user,"STAR").isEmpty()||!"APPROVED".equals(r.getStatus())||r.getGrantedUntil()==null||!r.getGrantedUntil().isAfter(Instant.now()))forbid("Emergency access is not active");return r;}
 private void refresh(EmergencyAccessRequestEntity r){Instant now=Instant.now();if("PENDING".equals(r.getStatus())&&!r.getExpiresAt().isAfter(now)||"APPROVED".equals(r.getStatus())&&(r.getGrantedUntil()==null||!r.getGrantedUntil().isAfter(now))){r.setStatus("EXPIRED");requests.save(r);}}
 private void event(EmergencyAccessRequestEntity r,Long actor,String action,Long resource){var e=new EmergencyAccessEventEntity();e.setRequestId(r.getId());e.setActorUserId(actor);e.setAction(action);e.setResourceId(resource);events.save(e);}
 private Person person(TrustedPersonEntity x){return publicPerson(x.getTrustedUserId(),x.getKind(),x.getCreatedAt());} private Person publicPerson(Long id,String kind,Instant at){return new Person(id,name(id),profiles.findById(id).map(x->x.getProfilePhoto()).orElse(null),kind,follows.countByRoleModelUserId(id),at);}
 private EmergencyRequest dto(EmergencyAccessRequestEntity r){return new EmergencyRequest(r.getId(),r.getOwnerUserId(),name(r.getOwnerUserId()),r.getRequesterUserId(),name(r.getRequesterUserId()),r.getReason(),r.getStatus(),(int)approvals.countByRequestIdAndApprovedTrue(r.getId()),r.getRequiredApprovals(),r.getCreatedAt(),r.getExpiresAt(),r.getGrantedUntil());}
 private String name(Long id){UserEntity x=users.findById(id).orElseThrow();String n=((x.getFirstName()==null?"":x.getFirstName())+" "+(x.getSurname()==null?"":x.getSurname())).trim();return n.isBlank()?x.getUsername():n;} private String kind(String v){String k=v==null?"":v.trim().toUpperCase();if(!Set.of("STAR","ROLE_MODEL").contains(k))bad("Choose STAR or ROLE_MODEL");return k;} private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);}private void forbid(String m){throw new ResponseStatusException(HttpStatus.FORBIDDEN,m);}
}
