package com.myaaptha.domain.person;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;import com.fasterxml.jackson.databind.*;import org.junit.jupiter.api.Test;import org.springframework.beans.factory.annotation.Autowired;import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;import org.springframework.boot.test.context.SpringBootTest;import org.springframework.http.*;import org.springframework.test.web.servlet.*;
@SpringBootTest @AutoConfigureMockMvc class PersonProfileControllerTest {@Autowired MockMvc mvc;@Autowired ObjectMapper json;
 @Test void profileIsViewableAndPrivateRecordAndMemoriesRequireRelationship()throws Exception{JsonNode owner=user("person-owner","+15550880101","Person","Owner"),person=user("person-target","+15550880102","Person","Target"),stranger=user("person-stranger","+15550880103","Person","Stranger");String ownerToken=login(owner),strangerToken=login(stranger);long personId=person.get("id").asLong();
  mvc.perform(get("/api/people/"+personId+"/profile").header(HttpHeaders.AUTHORIZATION,bearer(strangerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.displayName").value("Person Target")).andExpect(jsonPath("$.privateRecord.notes").value(org.hamcrest.Matchers.nullValue()));
  mvc.perform(put("/api/people/"+personId+"/record").header(HttpHeaders.AUTHORIZATION,bearer(strangerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"notes\":\"private\"}")).andExpect(status().isForbidden());
  mvc.perform(post("/api/network/relationships").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"relatedUserId\":"+personId+",\"type\":\"Friend\",\"visibilityScope\":\"FRIENDS\"}")).andExpect(status().isOk());
  mvc.perform(put("/api/people/"+personId+"/record").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"nickname\":\"PT\",\"contactPhone\":\"+15550001111\",\"occupation\":\"Engineer\",\"importantDates\":\"Anniversary 1 June\",\"notes\":\"Met at university\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.privateRecord.nickname").value("PT")).andExpect(jsonPath("$.privateRecord.notes").value("Met at university"));
  MvcResult memory=mvc.perform(multipart("/api/people/"+personId+"/memories").param("title","Graduation day").param("note","A proud day").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.title").value("Graduation day")).andReturn();long memoryId=json.readTree(memory.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(get("/api/people/"+personId+"/profile").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.memories[0].note").value("A proud day"));
  mvc.perform(delete("/api/people/"+personId+"/memories/"+memoryId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isNoContent());
 }
 private JsonNode user(String username,String phone,String first,String last)throws Exception{MvcResult r=mvc.perform(post("/api/users").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(new UserPayload(username,phone,"secret123",first,last,"Test")))).andExpect(status().isOk()).andReturn();return json.readTree(r.getResponse().getContentAsString());}private String login(JsonNode user)throws Exception{MvcResult r=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"identifier\":\""+user.get("phoneNumber").asText()+"\",\"password\":\"secret123\"}")).andExpect(status().isOk()).andReturn();return json.readTree(r.getResponse().getContentAsString()).get("accessToken").asText();}private String bearer(String t){return"Bearer "+t;}private record UserPayload(String username,String phoneNumber,String password,String firstName,String surname,String location){}
}
