'use client';
import Link from 'next/link';import {FormEvent,useCallback,useEffect,useState} from 'react';import EmergencyStart from './EmergencyStart';import {addTrustedPerson,decideEmergencyAccess,EmergencyDocument,EmergencyRequest,fetchEmergencyDocumentMedia,fetchEmergencyDocuments,fetchEmergencyRequests,fetchRoleModels,fetchTrustedPeople,followRoleModel,removeTrustedPerson,searchNetworkPeople,TrustedPerson} from '../lib/api';
export default function TrustPage(){
 const[stars,setStars]=useState<TrustedPerson[]>([]),[models,setModels]=useState<TrustedPerson[]>([]),[discover,setDiscover]=useState<TrustedPerson[]>([]),[requests,setRequests]=useState<EmergencyRequest[]>([]),[docs,setDocs]=useState<EmergencyDocument[]>([]),[query,setQuery]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const[a,b,c,d]=await Promise.all([fetchTrustedPeople('STAR'),fetchTrustedPeople('ROLE_MODEL'),fetchRoleModels(),fetchEmergencyRequests()]);setStars(a);setModels(b);setDiscover(c);setRequests(d);}catch(e){setMessage(e instanceof Error?e.message:'Could not load the Trust center.');}},[]);useEffect(()=>{void load();},[load]);
 async function add(event:FormEvent,kind:'STAR'|'ROLE_MODEL'){event.preventDefault();setBusy(true);try{const found=await searchNetworkPeople(query.trim());if(!found[0])throw new Error('No matching member found.');await addTrustedPerson(found[0].id,kind);setQuery('');setMessage(kind==='STAR'?'Star Member added. Add at least two for emergency verification.':'Role Model added; members can follow them without seeing private contact details.');await load();}catch(e){setMessage(e instanceof Error?e.message:'Could not add member.');}finally{setBusy(false);}}
 async function openDocument(d:EmergencyDocument){const blob=await fetchEmergencyDocumentMedia(d.mediaUrl);const url=URL.createObjectURL(blob);window.open(url,'_blank','noopener,noreferrer');window.setTimeout(()=>URL.revokeObjectURL(url),60000);}
 const people=(items:TrustedPerson[],removable=false)=><div className="trust-people">{items.map(x=><div key={x.userId}><span>{x.kind==='STAR'?'★':'◇'}</span><b>{x.displayName}</b>{removable?<button onClick={async()=>{await removeTrustedPerson(x.userId,'STAR');await load();}}>Remove</button>:<small>{x.followerCount} followers</small>}</div>)}</div>;
 return <main className="trust-page"><header className="trust-hero"><div><small>SAFETY & INSPIRATION</small><h1>Your Trust center</h1><p>Choose the people who protect your life records and the people who inspire your community.</p></div><span>★</span></header>{message&&<p className="trust-message" role="status">{message}</p>}<EmergencyStart onStarted={load}/>
 <section className="trust-grid"><article className="card trust-panel"><h2>Star Members</h2><p>Up to five trusted people. Emergency access requires two Stars and lasts one hour.</p><form onSubmit={e=>add(e,'STAR')}><input value={query} onChange={e=>setQuery(e.target.value)} required placeholder="Search by name, phone or location"/><button className="btn btn-primary" disabled={busy}>Add Star</button></form>{people(stars,true)}</article><article className="card trust-panel"><h2>My Role Models</h2><p>People you endorse for others to follow and contact inside CircleNet. Their phone and email stay private.</p><form onSubmit={e=>add(e,'ROLE_MODEL')}><input value={query} onChange={e=>setQuery(e.target.value)} required placeholder="Search for a member"/><button className="btn btn-primary" disabled={busy}>Add Role Model</button></form>{people(models)}</article></section>
 <section className="card trust-panel"><h2>Discover Role Models</h2><div className="role-model-grid">{discover.map(x=><article key={x.userId}><div className="role-avatar">{x.displayName.slice(0,2).toUpperCase()}</div><h3>{x.displayName}</h3><p>{x.followerCount} followers · Contact details private</p><div><button className="btn btn-primary" onClick={async()=>{await followRoleModel(x.userId);await load();}}>Follow</button><Link className="btn btn-secondary" href={`/messages?userId=${x.userId}`}>Message</Link></div></article>)}</div></section>
 <section className="card trust-panel"><h2>Emergency requests</h2><p>Requests expire after 24 hours. Access activates only after two independent Star approvals.</p>{requests.map(r=><article className="emergency-request" key={r.id}><div><b>{r.requesterName} → {r.ownerName}</b><span className={`trust-status status-${r.status.toLowerCase()}`}>{r.status}</span><p>{r.reason}</p><small>{r.approvals}/{r.requiredApprovals} approvals</small></div>{r.status==='PENDING'&&<div><button className="btn btn-primary" onClick={async()=>{await decideEmergencyAccess(r.id,true);await load();}}>Verify & approve</button><button className="btn btn-secondary" onClick={async()=>{await decideEmergencyAccess(r.id,false);await load();}}>Reject</button></div>}{r.status==='APPROVED'&&<button className="btn btn-primary" onClick={async()=>setDocs(await fetchEmergencyDocuments(r.id))}>View emergency documents</button>}</article>)}{docs.length>0&&<div className="emergency-docs"><h3>Time-limited emergency documents</h3>{docs.map(d=><button key={d.id} onClick={()=>void openDocument(d)}><b>{d.mediaName}</b><span>{d.caption||'Private document'}</span></button>)}</div>}</section></main>;
}
