package com.myaaptha.domain.circle;

import com.myaaptha.domain.circle.model.CircleEntity;
import com.myaaptha.domain.circle.model.CirclePostEntity;
import com.myaaptha.domain.network.dto.CirclePostDto;
import com.myaaptha.domain.profile.UserProfileRepository;
import com.myaaptha.domain.user.UserRepository;
import com.myaaptha.domain.user.model.UserEntity;
import com.myaaptha.domain.notification.NotificationCommand;
import com.myaaptha.domain.notification.NotificationService;
import java.util.*;
import java.time.Instant;
import org.springframework.core.io.Resource;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.server.ResponseStatusException;

@Service @Transactional
public class CircleConversationService {
  private final CircleRepository circles; private final CirclePostRepository posts; private final UserRepository users;
  private final UserProfileRepository profiles; private final CircleMediaStorage storage; private final NotificationService notificationService; private final CirclePostReactionRepository reactions; private final CirclePostReadRepository reads;
  private static final Set<String> ALLOWED_REACTIONS=Set.of("\uD83D\uDC4D","\u2764\uFE0F","\uD83D\uDE02","\uD83D\uDE2E","\uD83D\uDE22","\uD83D\uDE4F");
  public CircleConversationService(CircleRepository circles,CirclePostRepository posts,UserRepository users,UserProfileRepository profiles,CircleMediaStorage storage,NotificationService notificationService,CirclePostReactionRepository reactions,CirclePostReadRepository reads){this.circles=circles;this.posts=posts;this.users=users;this.profiles=profiles;this.storage=storage;this.notificationService=notificationService;this.reactions=reactions;this.reads=reads;}

  public List<CirclePostDto> posts(Long userId,Long circleId){memberCircle(userId,circleId);var values=posts.findByCircleIdOrderByCreatedAtAsc(circleId);for(var post:values)if(!userId.equals(post.getAuthorUserId())&&!reads.existsByPostIdAndUserId(post.getId(),userId)){var read=new com.myaaptha.domain.circle.model.CirclePostReadEntity();read.setPostId(post.getId());read.setUserId(userId);reads.save(read);}return values.stream().map(post->dto(post,userId)).toList();}
  @Transactional(readOnly=true) public Map<Long,Long> unreadCounts(Long userId){Map<Long,Long> result=new LinkedHashMap<>();for(var circle:circles.findAll())if(circle.getMemberUserIds().contains(userId)){long count=posts.findByCircleIdOrderByCreatedAtAsc(circle.getId()).stream().filter(post->!userId.equals(post.getAuthorUserId())&&!reads.existsByPostIdAndUserId(post.getId(),userId)).count();result.put(circle.getId(),count);}return result;}
  public CirclePostDto create(Long userId,Long circleId,Long parentPostId,String message,MultipartFile file){
    CircleEntity circle=memberCircle(userId,circleId); assertCanPost(circle,userId);
    String clean=message==null?"":message.trim(); if(clean.length()>4000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Message must be 4000 characters or less");
    CirclePostEntity parent=null; if(parentPostId!=null){parent=posts.findById(parentPostId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found"));if(!circleId.equals(parent.getCircleId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Reply must belong to this circle");if(parent.getDeletedAt()!=null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Deleted messages cannot receive replies");}
    if(clean.isBlank()&&(file==null||file.isEmpty()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Write a message or choose a file");
    CirclePostEntity post=new CirclePostEntity();post.setCircleId(circleId);post.setAuthorUserId(userId);post.setParentPostId(parent==null?null:parent.getId());post.setMessage(clean);
    if(file!=null&&!file.isEmpty()){var media=storage.store(userId,file);post.setAttachmentKey(media.key());post.setAttachmentName(media.name());post.setAttachmentType(media.type());post.setAttachmentSize(media.size());}
    post=posts.save(post); UserEntity author=users.findById(userId).orElseThrow(); String authorName=name(author);
    for(Long memberId:circle.getMemberUserIds()) if(!memberId.equals(userId)) notificationService.notify(new NotificationCommand(memberId,"CIRCLE_MESSAGE",circle.getName(),authorName+": "+(clean.isBlank()?"Sent an attachment":clean),"/dashboard?circleId="+circleId,"CIRCLE_POST",post.getId()));
    return dto(post,userId);
  }
  public CirclePostDto edit(Long userId,Long circleId,Long postId,String message){memberCircle(userId,circleId);CirclePostEntity post=ownedPost(userId,circleId,postId);if(post.getDeletedAt()!=null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Deleted messages cannot be edited");String clean=message==null?"":message.trim();if(clean.length()>4000)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Message must be 4000 characters or less");if(clean.isBlank()&&post.getAttachmentKey()==null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"A message cannot be empty");post.setMessage(clean);post.setEditedAt(Instant.now());return dto(posts.save(post),userId);}
  public CirclePostDto delete(Long userId,Long circleId,Long postId){memberCircle(userId,circleId);CirclePostEntity post=ownedPost(userId,circleId,postId);if(post.getDeletedAt()==null){if(post.getAttachmentKey()!=null)storage.delete(post.getAttachmentKey());post.setAttachmentKey(null);post.setAttachmentName(null);post.setAttachmentType(null);post.setAttachmentSize(null);post.setMessage("");post.setDeletedAt(Instant.now());}return dto(posts.save(post),userId);}
  @Transactional(readOnly=true) public List<CirclePostDto> search(Long userId,Long circleId,String query){memberCircle(userId,circleId);String q=query==null?"":query.trim().toLowerCase();if(q.isBlank())return List.of();return posts.findByCircleIdOrderByCreatedAtAsc(circleId).stream().filter(post->post.getDeletedAt()==null&&((post.getMessage()!=null&&post.getMessage().toLowerCase().contains(q))||(post.getAttachmentName()!=null&&post.getAttachmentName().toLowerCase().contains(q)))).map(post->dto(post,userId)).toList();}
  public CirclePostDto react(Long userId,Long circleId,Long postId,String emoji){memberCircle(userId,circleId);CirclePostEntity post=posts.findById(postId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found"));if(!circleId.equals(post.getCircleId()))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found");if(post.getDeletedAt()!=null)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Deleted messages cannot receive reactions");String clean=emoji==null?"":emoji.trim();if(!clean.isEmpty()&&!ALLOWED_REACTIONS.contains(clean))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Choose a supported reaction");var existing=reactions.findByPostIdAndUserId(postId,userId);if(clean.isEmpty())existing.ifPresent(reactions::delete);else if(existing.isPresent()){existing.get().setEmoji(clean);reactions.save(existing.get());}else{var reaction=new com.myaaptha.domain.circle.model.CirclePostReactionEntity();reaction.setPostId(postId);reaction.setUserId(userId);reaction.setEmoji(clean);reactions.save(reaction);}return dto(post,userId);}
  @Transactional(readOnly=true) public Attachment attachment(Long userId,Long circleId,Long postId){memberCircle(userId,circleId);CirclePostEntity post=posts.findById(postId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found"));if(!circleId.equals(post.getCircleId())||post.getAttachmentKey()==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Attachment not found");return new Attachment(storage.load(post.getAttachmentKey()),post.getAttachmentName(),post.getAttachmentType());}
  private CircleEntity memberCircle(Long userId,Long circleId){CircleEntity circle=circles.findById(circleId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Circle not found"));if(!circle.getMemberUserIds().contains(userId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Only circle members can view this conversation");return circle;}
  private void assertCanPost(CircleEntity circle,Long userId){if("ADMINS_ONLY".equals(circle.getPostingPermission())&&!circle.getAdminUserIds().contains(userId))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Only circle admins can post messages");}
  private CirclePostEntity ownedPost(Long userId,Long circleId,Long postId){CirclePostEntity post=posts.findById(postId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found"));if(!circleId.equals(post.getCircleId()))throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Message not found");if(!userId.equals(post.getAuthorUserId()))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Only the author can change this message");return post;}
  private CirclePostDto dto(CirclePostEntity post,Long currentUserId){UserEntity author=users.findById(post.getAuthorUserId()).orElseThrow();String name=((author.getFirstName()==null?"":author.getFirstName())+" "+(author.getSurname()==null?"":author.getSurname())).trim();if(name.isBlank())name=author.getUsername();String photo=profiles.findById(author.getId()).map(p->p.getProfilePhoto()).orElse(null);String url=post.getAttachmentKey()==null?null:"/api/network/circles/"+post.getCircleId()+"/posts/"+post.getId()+"/attachment";Map<String,Long> counts=new LinkedHashMap<>();String mine=null;for(var reaction:reactions.findByPostId(post.getId())){counts.merge(reaction.getEmoji(),1L,Long::sum);if(currentUserId.equals(reaction.getUserId()))mine=reaction.getEmoji();}return new CirclePostDto(post.getId(),post.getCircleId(),post.getParentPostId(),author.getId(),name,photo,post.getDeletedAt()==null?post.getMessage():"",url,post.getAttachmentName(),post.getAttachmentType(),post.getAttachmentSize(),post.getCreatedAt(),post.getEditedAt(),post.getDeletedAt(),counts,mine,reads.countByPostId(post.getId()),currentUserId.equals(author.getId()));}
  public record Attachment(Resource resource,String name,String type){}
  private String name(UserEntity user){String value=((user.getFirstName()==null?"":user.getFirstName())+" "+(user.getSurname()==null?"":user.getSurname())).trim();return value.isBlank()?user.getUsername():value;}
}
