'use client';
import Link from 'next/link';
import Image from 'next/image';
import { ChangeEvent, useEffect, useState } from 'react';
import { fetchUserProfile, hasAuthSession, removeGalleryPhoto, removeProfilePhoto, saveUserProfile, uploadGalleryPhoto, uploadProfilePhoto, UserProfile } from '../lib/api';
import { useRouter } from 'next/navigation';

const blank = { firstName:'',surname:'',email:'',phoneNumber:'',location:'',dateOfBirth:'',gender:'',bio:'',addressLine1:'',addressLine2:'',city:'',state:'',postalCode:'',country:'',alternatePhone:'',website:'',whatsapp:'',linkedin:'',facebook:'',instagram:'',xHandle:'',highestQualification:'',institution:'',fieldOfStudy:'',graduationYear:'',employmentStatus:'',employer:'',jobTitle:'',industry:'',workLocation:'',profilePhoto:null,photos:[] } as UserProfile;
const fields: Record<string, Array<[string,string,string?]>> = {
  'Personal details': [['firstName','First name'],['surname','Surname'],['email','Email','email'],['phoneNumber','Mobile number','tel'],['dateOfBirth','Date of birth','date'],['gender','Gender'],['location','General location'],['bio','About me']],
  'Address': [['addressLine1','Address line 1'],['addressLine2','Address line 2'],['city','City'],['state','State'],['postalCode','Postal code'],['country','Country']],
  'Communication & social media': [['alternatePhone','Alternate phone','tel'],['website','Website','url'],['whatsapp','WhatsApp'],['linkedin','LinkedIn','url'],['facebook','Facebook','url'],['instagram','Instagram'],['xHandle','X / Twitter handle']],
  'Education': [['highestQualification','Highest qualification'],['institution','School / College / University'],['fieldOfStudy','Field of study'],['graduationYear','Graduation year']],
  'Employment': [['employmentStatus','Employment status'],['employer','Employer / Organizations (separate multiple with commas)'],['jobTitle','Job title'],['industry','Industry'],['workLocation','Work location']],
};

export default function ProfilePage(){
 const router=useRouter(); const [profile,setProfile]=useState<UserProfile>(blank); const [message,setMessage]=useState(''); const [messageTone,setMessageTone]=useState<'error'|'success'>('error'); const [busy,setBusy]=useState(true);
 useEffect(()=>{if(!hasAuthSession()){router.replace('/auth');return;}fetchUserProfile().then(p=>setProfile({...blank,...p,photos:p.photos||[]})).catch(()=>{setMessageTone('error');setMessage('Unable to load profile.');}).finally(()=>setBusy(false));},[router]);
 const set=(key:string,value:string|string[]|null)=>setProfile(p=>({...p,[key]:value}));
 const validFile=(file:File)=>{if(!file.type.startsWith('image/')||file.size>5*1024*1024)throw new Error('Choose a JPG, PNG or WebP image under 5 MB.');};
 const profilePhoto=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;setBusy(true);try{validFile(file);setProfile(await uploadProfilePhoto(file));setMessageTone('success');setMessage('Profile photo uploaded successfully.');}catch(err){setMessageTone('error');setMessage((err as Error).message);}finally{setBusy(false);e.target.value='';}};
 const gallery=async(e:ChangeEvent<HTMLInputElement>)=>{const files=Array.from(e.target.files||[]);setBusy(true);try{let updated=profile;for(const file of files){validFile(file);updated=await uploadGalleryPhoto(file);}setProfile(updated);setMessageTone('success');setMessage('Gallery photos uploaded successfully.');}catch(err){setMessageTone('error');setMessage((err as Error).message);}finally{setBusy(false);e.target.value='';}};
 const saveSection=async(title:string)=>{setBusy(true);setMessage('');try{setProfile(await saveUserProfile(profile));setMessageTone('success');setMessage(`${title} saved successfully.`);}catch(err){setMessageTone('error');setMessage(err instanceof Error?err.message:`Unable to save ${title.toLowerCase()}.`);}finally{setBusy(false);}};
 return <main className="container profile-page"><header className="profile-header"><div><p className="eyebrow">MY MYAAPTHA PROFILE</p><h1>My profile</h1><p>Keep your personal, communication, education and employment details together.</p></div><Link className="btn btn-secondary" href="/dashboard">Back to dashboard</Link></header>
 {busy&&!profile.phoneNumber?<p className="network-message">Loading profile…</p>:<div className="profile-form">{message&&<p className={`profile-message ${messageTone==='error'?'error-message':'success-message'}`} role={messageTone==='error'?'alert':'status'}>{message}</p>}<section className="profile-photo-card card"><div className="profile-photo-preview">{profile.profilePhoto?<Image unoptimized width={112} height={112} src={profile.profilePhoto as string} alt="Profile"/>:<span>{String(profile.firstName||'U').charAt(0)}</span>}</div><div><h2>Profile photo</h2><p>Stored outside the application package. JPG, PNG or WebP, maximum 5 MB.</p><label className="btn btn-secondary">{busy?'Uploading…':'Upload photo'}<input hidden disabled={busy} type="file" accept="image/jpeg,image/png,image/webp" onChange={profilePhoto}/></label>{profile.profilePhoto&&<button type="button" className="action-tag action-tag-danger" onClick={async()=>{setBusy(true);try{setProfile(await removeProfilePhoto());setMessageTone('success');setMessage('Profile photo removed.');}catch(err){setMessageTone('error');setMessage((err as Error).message);}finally{setBusy(false);}}}>Remove</button>}</div></section>
 {Object.entries(fields).map(([title,items])=><section className="card profile-section" key={title}><div className="profile-section-heading"><h2>{title}</h2><button type="button" className="btn btn-primary" disabled={busy} onClick={()=>saveSection(title)}>{busy?'Saving…':`Save ${title}`}</button></div><div className="profile-fields">{items.map(([key,label,type])=><label key={key} className={key==='bio'?'profile-wide':''}><span>{label}</span>{key==='bio'?<textarea rows={4} value={String(profile[key]||'')} onChange={e=>set(key,e.target.value)}/>:<input type={type||'text'} readOnly={key==='phoneNumber'} value={String(profile[key]||'')} onChange={e=>set(key,e.target.value)}/>}</label>)}</div></section>)}
 <section className="card profile-section"><div className="profile-section-heading"><div><h2>Photo gallery</h2><p>Add up to eight externally stored photos, maximum 5 MB each.</p></div><label className="btn btn-secondary">{busy?'Uploading…':'Upload photos'}<input hidden disabled={busy} multiple type="file" accept="image/jpeg,image/png,image/webp" onChange={gallery}/></label></div><div className="profile-gallery">{(profile.photos as string[]).map((photo,index)=><figure key={photo}><Image unoptimized fill sizes="(max-width: 820px) 50vw, 180px" src={photo} alt={`Gallery photo ${index+1}`}/><button type="button" className="action-tag action-tag-danger" onClick={async()=>{setBusy(true);try{setProfile(await removeGalleryPhoto(index));setMessageTone('success');setMessage('Gallery photo removed.');}catch(err){setMessageTone('error');setMessage((err as Error).message);}finally{setBusy(false);}}}>Remove</button></figure>)}</div></section></div>}</main>;
}
