package com.myaaptha.domain.social;

import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.fasterxml.jackson.databind.*; import org.junit.jupiter.api.Test; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.http.*; import org.springframework.mock.web.MockMultipartFile; import org.springframework.test.web.servlet.*;

@SpringBootTest @AutoConfigureMockMvc class SocialControllerTest {
 @Autowired MockMvc mvc; @Autowired ObjectMapper json;
 @Test void socialPostStoryReactionCommentAndPrivacyLifecycle() throws Exception {
  JsonNode owner=user("social-owner","+15550990101","Social","Owner"), friend=user("social-friend","+15550990102","Social","Friend"), stranger=user("social-stranger","+15550990103","Social","Stranger");String ownerToken=login(owner),friendToken=login(friend),strangerToken=login(stranger);
  mvc.perform(post("/api/network/relationships").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"relatedUserId\":"+friend.get("id").asLong()+",\"type\":\"Friend\",\"visibilityScope\":\"FRIENDS\"}")).andExpect(status().isOk());
  MvcResult privateEntry=mvc.perform(multipart("/api/social/posts").file(new MockMultipartFile("file","journal.pdf","application/pdf",new byte[]{37,80,68,70,45,49,46,52})).param("caption","A private diary entry").param("audience","PRIVATE").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.audience").value("PRIVATE")).andReturn();long privateId=json.readTree(privateEntry.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(get("/api/social/feed").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(privateId));
  mvc.perform(get("/api/social/feed").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(get("/api/social/posts/"+privateId+"/media").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isForbidden());
  mvc.perform(delete("/api/social/posts/"+privateId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isNoContent());
  MvcResult created=mvc.perform(multipart("/api/social/posts").file(new MockMultipartFile("file","family.png","image/png",new byte[]{(byte)137,80,78,71,13,10,26,10})).param("caption","Our family moment").param("audience","RELATIONSHIPS").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.caption").value("Our family moment")).andReturn();long postId=json.readTree(created.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(post("/api/social/posts/"+postId+"/share").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"destinationType\":\"DIRECT\",\"targetId\":"+friend.get("id").asLong()+",\"message\":\"See this\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.destinationType").value("DIRECT"));
  mvc.perform(get("/api/network/messages/with/"+owner.get("id").asLong()).header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].message").value(org.hamcrest.Matchers.containsString("/feed?postId="+postId)));
  MvcResult circle=mvc.perform(post("/api/network/circles").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"name\":\"Shared moments\",\"description\":\"Posts\"}")).andExpect(status().isOk()).andReturn();long circleId=json.readTree(circle.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(post("/api/social/posts/"+postId+"/share").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"destinationType\":\"CIRCLE\",\"targetId\":"+circleId+",\"message\":\"For our circle\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.destinationType").value("CIRCLE"));
  mvc.perform(get("/api/network/circles/"+circleId+"/posts").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].message").value(org.hamcrest.Matchers.containsString("/feed?postId="+postId)));
  mvc.perform(get("/api/social/feed").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(postId));
  MvcResult report=mvc.perform(post("/api/moderation/reports").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"reportedUserId\":"+owner.get("id").asLong()+",\"entityType\":\"SOCIAL_POST\",\"entityId\":"+postId+",\"reason\":\"SPAM\",\"details\":\"Test report\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("OPEN")).andReturn();long reportId=json.readTree(report.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(get("/api/moderation/reports/mine").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].entityId").value(postId));
  mvc.perform(get("/api/moderation/reports/mine").header(HttpHeaders.AUTHORIZATION,bearer(strangerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(post("/api/moderation/reports").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"reportedUserId\":"+owner.get("id").asLong()+",\"entityType\":\"SOCIAL_POST\",\"entityId\":"+postId+",\"reason\":\"OTHER\"}")).andExpect(status().isBadRequest());
  MvcResult adminLogin=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"identifier\":\"admin@myaaptha.ai\",\"password\":\"admin123\"}")).andExpect(status().isOk()).andReturn();String adminToken=json.readTree(adminLogin.getResponse().getContentAsString()).get("accessToken").asText();
  mvc.perform(get("/api/moderation/reports").header(HttpHeaders.AUTHORIZATION,bearer(adminToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(reportId));
  mvc.perform(put("/api/moderation/reports/"+reportId).header(HttpHeaders.AUTHORIZATION,bearer(adminToken)).contentType(MediaType.APPLICATION_JSON).content("{\"status\":\"RESOLVED\",\"notes\":\"Reviewed in test\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.status").value("RESOLVED")).andExpect(jsonPath("$.moderatorNotes").value("Reviewed in test"));
  mvc.perform(post("/api/social/posts/"+postId+"/save").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$.savedByMe").value(true));
  mvc.perform(get("/api/social/saved").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(postId)).andExpect(jsonPath("$[0].savedByMe").value(true));
  mvc.perform(get("/api/social/feed").header(HttpHeaders.AUTHORIZATION,bearer(strangerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(put("/api/notifications/preferences").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"emailEnabled\":true,\"smsEnabled\":true,\"pushEnabled\":true,\"messagesEnabled\":true,\"circlesEnabled\":true,\"relationshipsEnabled\":true,\"callsEnabled\":true,\"invitationsEnabled\":true,\"socialEnabled\":false}")).andExpect(status().isOk()).andExpect(jsonPath("$.socialEnabled").value(false));
  mvc.perform(post("/api/social/posts/"+postId+"/like").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$.likedByMe").value(true)).andExpect(jsonPath("$.likeCount").value(1));
  mvc.perform(get("/api/notifications").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[?(@.type == 'SOCIAL_LIKE')]").isEmpty());
  mvc.perform(put("/api/notifications/preferences").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"emailEnabled\":true,\"smsEnabled\":true,\"pushEnabled\":true,\"messagesEnabled\":true,\"circlesEnabled\":true,\"relationshipsEnabled\":true,\"callsEnabled\":true,\"invitationsEnabled\":true,\"socialEnabled\":true}")).andExpect(status().isOk()).andExpect(jsonPath("$.socialEnabled").value(true));
  mvc.perform(post("/api/social/posts/"+postId+"/comments").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"message\":\"Beautiful!\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.message").value("Beautiful!"));
  mvc.perform(get("/api/notifications").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[?(@.type == 'SOCIAL_COMMENT')]").isNotEmpty());
  mvc.perform(get("/api/social/posts/"+postId+"/media").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(content().contentType("image/png"));
  MvcResult story=mvc.perform(multipart("/api/social/stories").file(new MockMultipartFile("file","story.png","image/png",new byte[]{(byte)137,80,78,71,13,10,26,10})).param("caption","Today").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.expiresAt").exists()).andReturn();long storyId=json.readTree(story.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(post("/api/social/stories/"+storyId+"/view").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$.viewedByMe").value(true)).andExpect(jsonPath("$.viewCount").value(1));
  mvc.perform(post("/api/social/stories/"+storyId+"/view").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$.viewCount").value(1));
  mvc.perform(get("/api/social/stories").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].viewedByMe").value(true)).andExpect(jsonPath("$[0].viewCount").value(1));
  mvc.perform(get("/api/social/stories").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].viewedByMe").value(false)).andExpect(jsonPath("$[0].viewCount").value(1));
  mvc.perform(post("/api/social/stories/"+storyId+"/view").header(HttpHeaders.AUTHORIZATION,bearer(strangerToken))).andExpect(status().isForbidden());
  mvc.perform(post("/api/privacy/blocks").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"userId\":"+owner.get("id").asLong()+"}")).andExpect(status().isOk()).andExpect(jsonPath("$.displayName").value("Social Owner"));
  mvc.perform(get("/api/social/feed").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(get("/api/social/saved").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(get("/api/social/stories").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0]").doesNotExist());
  mvc.perform(get("/api/social/stories/"+storyId+"/media").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isForbidden());
  mvc.perform(multipart("/api/network/messages/with/"+friend.get("id").asLong()).param("message","Blocked message").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isForbidden());
  mvc.perform(post("/api/network/calls").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"recipientId\":"+friend.get("id").asLong()+",\"callType\":\"AUDIO\",\"offerSdp\":\"{}\"}")).andExpect(status().isForbidden());
  mvc.perform(delete("/api/privacy/blocks/"+owner.get("id").asLong()).header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isNoContent());
  MvcResult sent=mvc.perform(multipart("/api/network/messages/with/"+friend.get("id").asLong()).param("message","Original private update").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.deliveredAt").exists()).andReturn();long messageId=json.readTree(sent.getResponse().getContentAsString()).get("id").asLong();
  mvc.perform(get("/api/network/messages/conversations").header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].userId").value(owner.get("id").asLong())).andExpect(jsonPath("$[0].lastMessage").value("Original private update")).andExpect(jsonPath("$[0].unreadCount").value(1));
  mvc.perform(get("/api/network/messages/with/"+owner.get("id").asLong()).header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].readAt").exists());
  mvc.perform(put("/api/network/messages/with/"+friend.get("id").asLong()+"/"+messageId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken)).contentType(MediaType.APPLICATION_JSON).content("{\"message\":\"Edited private update\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.editedAt").exists());
  mvc.perform(post("/api/privacy/blocks").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"userId\":"+owner.get("id").asLong()+"}")).andExpect(status().isOk());
  mvc.perform(post("/api/network/messages/with/"+owner.get("id").asLong()+"/"+messageId+"/reaction").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"emoji\":\"👍\"}")).andExpect(status().isForbidden());
  mvc.perform(delete("/api/privacy/blocks/"+owner.get("id").asLong()).header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isNoContent());
  mvc.perform(post("/api/network/messages/with/"+owner.get("id").asLong()+"/"+messageId+"/reaction").header(HttpHeaders.AUTHORIZATION,bearer(friendToken)).contentType(MediaType.APPLICATION_JSON).content("{\"emoji\":\"👍\"}")).andExpect(status().isOk()).andExpect(jsonPath("$.reactions['👍']").value(1));
  mvc.perform(get("/api/network/messages/with/"+friend.get("id").asLong()+"/search").param("q","edited").header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$[0].id").value(messageId));
  mvc.perform(multipart("/api/network/messages/with/"+owner.get("id").asLong()).param("message","Reply received").param("replyToMessageId",String.valueOf(messageId)).header(HttpHeaders.AUTHORIZATION,bearer(friendToken))).andExpect(status().isOk()).andExpect(jsonPath("$.replyToMessageId").value(messageId));
  mvc.perform(delete("/api/network/messages/with/"+friend.get("id").asLong()+"/"+messageId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isOk()).andExpect(jsonPath("$.deletedAt").exists());
  mvc.perform(delete("/api/social/stories/"+storyId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isNoContent());mvc.perform(delete("/api/social/posts/"+postId).header(HttpHeaders.AUTHORIZATION,bearer(ownerToken))).andExpect(status().isNoContent());
 }
 private JsonNode user(String username,String phone,String first,String last)throws Exception{MvcResult r=mvc.perform(post("/api/users").contentType(MediaType.APPLICATION_JSON).content(json.writeValueAsString(new UserPayload(username,phone,"secret123",first,last,"Test")))).andExpect(status().isOk()).andReturn();return json.readTree(r.getResponse().getContentAsString());}
 private String login(JsonNode user)throws Exception{MvcResult r=mvc.perform(post("/api/auth/login").contentType(MediaType.APPLICATION_JSON).content("{\"identifier\":\""+user.get("phoneNumber").asText()+"\",\"password\":\"secret123\"}")).andExpect(status().isOk()).andReturn();return json.readTree(r.getResponse().getContentAsString()).get("accessToken").asText();} private String bearer(String t){return "Bearer "+t;} private record UserPayload(String username,String phoneNumber,String password,String firstName,String surname,String location){}
}
