package com.myaaptha.domain.social;

import com.myaaptha.domain.circle.CircleMediaStorage; import com.myaaptha.domain.circle.CircleRepository; import com.myaaptha.domain.circle.CircleConversationService;
import com.myaaptha.domain.message.DirectMessageService;
import com.myaaptha.domain.notification.*; import com.myaaptha.domain.profile.UserProfileRepository; import com.myaaptha.domain.relationship.RelationshipRepository;
import com.myaaptha.domain.social.model.*; import com.myaaptha.domain.user.UserRepository; import com.myaaptha.domain.user.model.UserEntity;
import com.myaaptha.domain.privacy.UserBlockRepository;
import java.time.*; import java.util.*; import org.springframework.core.io.Resource; import org.springframework.http.HttpStatus; import org.springframework.scheduling.annotation.Scheduled; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException;

@Service @Transactional public class SocialService {
 private static final Set<String> RELATIVE_TYPES=Set.of("wife","husband","mother","father","daughter","son","sister","brother","grandmother","grandfather","granddaughter","grandson","aunt","uncle","niece","nephew","cousin","relative","spouse","parent","child","sibling");
 private final SocialPostRepository posts; private final SocialCommentRepository comments; private final SocialStoryRepository stories; private final SocialStoryViewRepository storyViews; private final SocialLikeRepository likes; private final SocialSaveRepository saves; private final UserRepository users; private final UserProfileRepository profiles; private final RelationshipRepository relationships; private final CircleRepository circles; private final CircleMediaStorage media; private final NotificationService notifications; private final UserBlockRepository blocks; private final DirectMessageService directMessages; private final CircleConversationService circleMessages;
 public SocialService(SocialPostRepository p,SocialCommentRepository c,SocialStoryRepository s,SocialStoryViewRepository v,SocialLikeRepository l,SocialSaveRepository sv,UserRepository u,UserProfileRepository pr,RelationshipRepository r,CircleRepository cr,CircleMediaStorage m,NotificationService n,UserBlockRepository b,DirectMessageService dm,CircleConversationService cm){posts=p;comments=c;stories=s;storyViews=v;likes=l;saves=sv;users=u;profiles=pr;relationships=r;circles=cr;media=m;notifications=n;blocks=b;directMessages=dm;circleMessages=cm;}
 @Transactional(readOnly=true) public List<SocialDtos.Post> feed(Long viewer){return posts.findTop100ByOrderByCreatedAtDesc().stream().filter(p->canView(viewer,p)).map(p->postDto(p,viewer,true)).toList();}
 @Transactional(readOnly=true) public List<SocialDtos.Post> saved(Long viewer){Set<Long> ids=saves.postsFor(viewer);return posts.findTop100ByOrderByCreatedAtDesc().stream().filter(p->ids.contains(p.getId())&&canView(viewer,p)).map(p->postDto(p,viewer,true)).toList();}
 public SocialDtos.Post createPost(Long userId,String caption,String audience,Long circleId,MultipartFile file){users.findById(userId).orElseThrow();String text=clean(caption,4000);if(text.isBlank()&&(file==null||file.isEmpty()))bad("Write a caption or choose media");String scope=scope(audience,true);if("CIRCLE".equals(scope)){var circle=circles.findById(circleId==null?-1L:circleId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Circle not found"));if(!circle.getOwnerUserId().equals(userId)&&!circle.getMemberUserIds().contains(userId))forbid();}else circleId=null;SocialPostEntity p=new SocialPostEntity();p.setAuthorUserId(userId);p.setCaption(text);p.setAudience(scope);p.setCircleId(circleId);if(file!=null&&!file.isEmpty()){var stored=media.store(userId,file);p.setMediaKey(stored.key());p.setMediaName(stored.name());p.setMediaType(stored.type());p.setMediaSize(stored.size());}return postDto(posts.save(p),userId,true);}
 public SocialDtos.Post updatePost(Long userId,Long postId,String caption){SocialPostEntity p=owned(userId,postId);p.setCaption(clean(caption,4000));if(p.getCaption().isBlank()&&p.getMediaKey()==null)bad("A post cannot be empty");p.setUpdatedAt(Instant.now());return postDto(posts.save(p),userId,true);}
 public void deletePost(Long userId,Long postId){SocialPostEntity p=owned(userId,postId);if(p.getMediaKey()!=null)media.delete(p.getMediaKey());posts.delete(p);}
 public SocialDtos.Post toggleLike(Long userId,Long postId){SocialPostEntity p=visible(userId,postId);Set<Long> current=likes.usersFor(postId);if(current.contains(userId))likes.remove(postId,userId);else{likes.add(postId,userId);if(!userId.equals(p.getAuthorUserId()))notifications.notify(new NotificationCommand(p.getAuthorUserId(),"SOCIAL_LIKE",name(userId)+" liked your post","Open your post to see the activity.","/feed?postId="+postId,"SOCIAL_POST",postId));}return postDto(p,userId,true);}
 public SocialDtos.Post toggleSave(Long userId,Long postId){SocialPostEntity p=visible(userId,postId);if(saves.contains(postId,userId))saves.remove(postId,userId);else saves.add(postId,userId);return postDto(p,userId,true);}
 public SocialDtos.ShareResult share(Long userId,Long postId,SocialDtos.ShareRequest request){SocialPostEntity p=visible(userId,postId);if(request==null||request.targetId()==null)bad("Choose a share destination");String type=request.destinationType()==null?"":request.destinationType().trim().toUpperCase();String note=clean(request.message(),1000);String preview=p.getCaption()==null||p.getCaption().isBlank()?"Shared media":p.getCaption();String text=(note.isBlank()?"":note+"\n\n")+"Shared post from "+name(p.getAuthorUserId())+": "+preview+"\n/feed?postId="+postId;if(text.length()>4000)text=text.substring(0,4000);if("DIRECT".equals(type)){if(!canView(request.targetId(),p))forbid();var sent=directMessages.send(userId,request.targetId(),text,null);return new SocialDtos.ShareResult(type,request.targetId(),sent.id());}if("CIRCLE".equals(type)){var circle=circles.findById(request.targetId()).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Circle not found"));if(!circle.getMemberUserIds().contains(userId))forbid();if(circle.getMemberUserIds().stream().anyMatch(member->!canView(member,p)))bad("Every circle member must already be allowed to view this post");var sent=circleMessages.create(userId,circle.getId(),null,text,null);return new SocialDtos.ShareResult(type,circle.getId(),sent.id());}bad("Choose a direct conversation or circle");return null;}
 public SocialDtos.Comment comment(Long userId,Long postId,String message){SocialPostEntity p=visible(userId,postId);String text=clean(message,1000);if(text.isBlank())bad("Write a comment");SocialCommentEntity c=new SocialCommentEntity();c.setPostId(postId);c.setAuthorUserId(userId);c.setMessage(text);c=comments.save(c);if(!userId.equals(p.getAuthorUserId()))notifications.notify(new NotificationCommand(p.getAuthorUserId(),"SOCIAL_COMMENT",name(userId)+" commented on your post",text,"/feed?postId="+postId,"SOCIAL_POST",postId));return commentDto(c,userId);}
 public void deleteComment(Long userId,Long postId,Long commentId){visible(userId,postId);SocialCommentEntity c=comments.findById(commentId).filter(x->x.getPostId().equals(postId)).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Comment not found"));SocialPostEntity p=posts.findById(postId).orElseThrow();if(!userId.equals(c.getAuthorUserId())&&!userId.equals(p.getAuthorUserId()))forbid();comments.delete(c);}
 @Transactional(readOnly=true) public List<SocialDtos.Story> activeStories(Long viewer){return stories.findByExpiresAtAfterOrderByCreatedAtDesc(Instant.now()).stream().filter(s->canViewStory(viewer,s)).map(s->storyDto(s,viewer)).toList();}
 public SocialDtos.Story createStory(Long userId,String caption,String audience,MultipartFile file){if(file==null||file.isEmpty())bad("Choose an image or video for the story");var stored=media.store(userId,file);if(stored.type()==null||(!stored.type().startsWith("image/")&&!stored.type().startsWith("video/"))){media.delete(stored.key());bad("Stories support images and videos only");}SocialStoryEntity s=new SocialStoryEntity();s.setAuthorUserId(userId);s.setCaption(clean(caption,1000));s.setAudience(scope(audience,false));s.setMediaKey(stored.key());s.setMediaName(stored.name());s.setMediaType(stored.type());s.setMediaSize(stored.size());s.setExpiresAt(Instant.now().plus(Duration.ofHours(24)));return storyDto(stories.save(s),userId);}
 public SocialDtos.Story viewStory(Long viewer,Long storyId){SocialStoryEntity s=stories.findById(storyId).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Story not found"));if(!canViewStory(viewer,s))forbid();if(!viewer.equals(s.getAuthorUserId())&&!storyViews.contains(storyId,viewer))storyViews.add(storyId,viewer);return storyDto(s,viewer);}
 public void deleteStory(Long userId,Long id){SocialStoryEntity s=stories.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Story not found"));if(!userId.equals(s.getAuthorUserId()))forbid();media.delete(s.getMediaKey());stories.delete(s);}
 @Scheduled(fixedDelayString="${myaaptha.social.story-cleanup-ms:3600000}") public void cleanupExpiredStories(){for(SocialStoryEntity story:stories.findTop100ByExpiresAtBeforeOrderByExpiresAt(Instant.now())){media.delete(story.getMediaKey());stories.delete(story);}}
 @Transactional(readOnly=true) public Attachment postMedia(Long viewer,Long id){SocialPostEntity p=visible(viewer,id);if(p.getMediaKey()==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Media not found");return new Attachment(media.load(p.getMediaKey()),p.getMediaName(),p.getMediaType());}
 @Transactional(readOnly=true) public Attachment storyMedia(Long viewer,Long id){SocialStoryEntity s=stories.findById(id).filter(x->x.getExpiresAt().isAfter(Instant.now())).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Story not found"));if(!canViewStory(viewer,s))forbid();return new Attachment(media.load(s.getMediaKey()),s.getMediaName(),s.getMediaType());}
 private SocialPostEntity visible(Long u,Long id){SocialPostEntity p=posts.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Post not found"));if(!canView(u,p))forbid();return p;} private SocialPostEntity owned(Long u,Long id){SocialPostEntity p=posts.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Post not found"));if(!u.equals(p.getAuthorUserId()))forbid();return p;}
 private boolean canView(Long u,SocialPostEntity p){if(!u.equals(p.getAuthorUserId())&&blocks.blockedEitherWay(u,p.getAuthorUserId()))return false;if(u.equals(p.getAuthorUserId())||"PUBLIC".equals(p.getAudience()))return true;if("PRIVATE".equals(p.getAudience()))return false;if("RELATIONSHIPS".equals(p.getAudience()))return connected(u,p.getAuthorUserId());if("FRIENDS".equals(p.getAudience()))return hasRelationshipType(u,p.getAuthorUserId(),Set.of("friend"));if("RELATIVES".equals(p.getAudience()))return hasRelationshipType(u,p.getAuthorUserId(),RELATIVE_TYPES);return circles.findById(p.getCircleId()).map(c->c.getOwnerUserId().equals(u)||c.getMemberUserIds().contains(u)).orElse(false);} private boolean connected(Long a,Long b){return relationships.findByOwnerUserIdAndRelatedUserId(a,b).isPresent()||relationships.findByOwnerUserIdAndRelatedUserId(b,a).isPresent();}
 private boolean hasRelationshipType(Long viewer,Long author,Set<String> types){return relationships.findByOwnerUserIdAndRelatedUserId(author,viewer).or(()->relationships.findByOwnerUserIdAndRelatedUserId(viewer,author)).map(r->r.getType()!=null&&types.contains(r.getType().trim().toLowerCase())).orElse(false);}
 private boolean canViewStory(Long viewer,SocialStoryEntity story){if(viewer.equals(story.getAuthorUserId()))return true;if(blocks.blockedEitherWay(viewer,story.getAuthorUserId()))return false;return "PUBLIC".equals(story.getAudience())||connected(viewer,story.getAuthorUserId());}
 private SocialDtos.Post postDto(SocialPostEntity p,Long u,boolean includeComments){Set<Long> liked=likes.usersFor(p.getId());List<SocialDtos.Comment> cs=includeComments?comments.findByPostIdOrderByCreatedAtAsc(p.getId()).stream().map(c->commentDto(c,u)).toList():List.of();return new SocialDtos.Post(p.getId(),p.getAuthorUserId(),name(p.getAuthorUserId()),photo(p.getAuthorUserId()),p.getCaption(),p.getAudience(),p.getCircleId(),p.getMediaKey()==null?null:"/api/social/posts/"+p.getId()+"/media",p.getMediaName(),p.getMediaType(),p.getMediaSize(),liked.size(),comments.countByPostId(p.getId()),liked.contains(u),saves.contains(p.getId(),u),p.getAuthorUserId().equals(u),p.getCreatedAt(),p.getUpdatedAt(),cs);}
 private SocialDtos.Comment commentDto(SocialCommentEntity c,Long u){return new SocialDtos.Comment(c.getId(),c.getAuthorUserId(),name(c.getAuthorUserId()),photo(c.getAuthorUserId()),c.getMessage(),c.getCreatedAt(),u.equals(c.getAuthorUserId()));} private SocialDtos.Story storyDto(SocialStoryEntity s,Long u){return new SocialDtos.Story(s.getId(),s.getAuthorUserId(),name(s.getAuthorUserId()),photo(s.getAuthorUserId()),s.getCaption(),s.getAudience(),"/api/social/stories/"+s.getId()+"/media",s.getMediaType(),s.getCreatedAt(),s.getExpiresAt(),storyViews.countFor(s.getId()),storyViews.contains(s.getId(),u),u.equals(s.getAuthorUserId()));}
 private String name(Long id){UserEntity x=users.findById(id).orElseThrow();String n=((x.getFirstName()==null?"":x.getFirstName())+" "+(x.getSurname()==null?"":x.getSurname())).trim();return n.isBlank()?x.getUsername():n;} private String photo(Long id){return profiles.findById(id).map(x->x.getProfilePhoto()).orElse(null);} private String scope(String value,boolean allowCircle){String v=value==null?(allowCircle?"PRIVATE":"RELATIONSHIPS"):value.trim().toUpperCase();Set<String> valid=allowCircle?Set.of("PRIVATE","PUBLIC","FRIENDS","RELATIVES","RELATIONSHIPS","CIRCLE"):Set.of("PUBLIC","RELATIONSHIPS");if(!valid.contains(v))bad("Choose a valid audience");return v;} private String clean(String v,int max){String x=v==null?"":v.trim();if(x.length()>max)bad("Text is too long");return x;} private void bad(String m){throw new ResponseStatusException(HttpStatus.BAD_REQUEST,m);} private void forbid(){throw new ResponseStatusException(HttpStatus.FORBIDDEN,"You do not have access to this content");}
 public record Attachment(Resource resource,String name,String type){}
}
