CREATE TABLE trusted_people (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  trusted_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  kind VARCHAR(20) NOT NULL CHECK (kind IN ('STAR','ROLE_MODEL')),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_trusted_people UNIQUE (owner_user_id, trusted_user_id, kind),
  CONSTRAINT chk_trusted_people_distinct CHECK (owner_user_id <> trusted_user_id)
);
CREATE INDEX idx_trusted_people_trusted ON trusted_people(trusted_user_id, kind);

CREATE TABLE role_model_follows (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  role_model_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uq_role_model_follow UNIQUE (follower_user_id, role_model_user_id),
  CONSTRAINT chk_role_model_follow_distinct CHECK (follower_user_id <> role_model_user_id)
);

CREATE TABLE emergency_access_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  requester_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  reason VARCHAR(1000) NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING','APPROVED','REJECTED','EXPIRED')),
  required_approvals INTEGER NOT NULL DEFAULT 2,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
  granted_until TIMESTAMP WITH TIME ZONE
);
CREATE INDEX idx_emergency_requests_owner ON emergency_access_requests(owner_user_id, status);

CREATE TABLE emergency_access_approvals (
  request_id BIGINT NOT NULL REFERENCES emergency_access_requests(id) ON DELETE CASCADE,
  approver_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  approved BOOLEAN NOT NULL,
  decided_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (request_id, approver_user_id)
);

CREATE TABLE emergency_access_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id BIGINT NOT NULL REFERENCES emergency_access_requests(id) ON DELETE CASCADE,
  actor_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  action VARCHAR(40) NOT NULL,
  resource_id BIGINT,
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
