CREATE TABLE financial_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  amount DECIMAL(15,2) NOT NULL,
  direction VARCHAR(12) NOT NULL,
  category VARCHAR(32) NOT NULL,
  merchant VARCHAR(160),
  description VARCHAR(500),
  occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
  source VARCHAR(20) NOT NULL,
  source_fingerprint VARCHAR(64),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT financial_direction_check CHECK (direction IN ('EXPENSE','INCOME')),
  CONSTRAINT financial_amount_check CHECK (amount > 0),
  CONSTRAINT financial_source_check CHECK (source IN ('MANUAL','SMS','IMPORT')),
  CONSTRAINT financial_source_unique UNIQUE (user_id, source_fingerprint)
);
CREATE INDEX financial_transactions_user_date_idx ON financial_transactions(user_id, occurred_at DESC);

