CREATE TABLE health_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  source_post_id BIGINT REFERENCES social_posts(id) ON DELETE SET NULL,
  report_name VARCHAR(200) NOT NULL,
  laboratory VARCHAR(200),
  collected_on DATE NOT NULL,
  notes VARCHAR(1000),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX health_reports_user_date_idx ON health_reports(user_id,collected_on DESC);
CREATE TABLE health_measurements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id BIGINT NOT NULL REFERENCES health_reports(id) ON DELETE CASCADE,
  metric_name VARCHAR(120) NOT NULL,
  measured_value DECIMAL(18,4) NOT NULL,
  unit VARCHAR(40) NOT NULL,
  reference_min DECIMAL(18,4),
  reference_max DECIMAL(18,4)
);
CREATE INDEX health_measurements_report_idx ON health_measurements(report_id);
